# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration
#
CommitMsg:
  MessageFormat:
    enabled: true
    pattern: '' # current regex was a bit wonky, so allow anything for now, but scrutinize commits in PR review.
    expected_pattern_message: "Commit messages must follow conventional commits format. For more info, check out: https://www.conventionalcommits.org/"
    sample_message: "<type>[(optional scope)]: <description>

[optional body]

[optional footer(s)]"
  TextWidth:
    enabled: true
    max_subject_width: 80
  CapitalizedSubject:
    enabled: false # First word of conventional commits is usually lower case.
  TrailingPeriod:
    enabled: false

PreCommit:
  ALL:
    exclude: &default_excludes
      - 'node_modules/**/*'
      - 'vendor/**/*'
  RuboCop:
    enabled: true
    command: ["bundle", "exec", "rubocop", "--raise-cop-error", "--fail-level", "A", "--extra-details", "--display-style-guide"]
    on_warn: fail
    problem_on_unmodified_line: warn
  CustomScript:
    enabled: true
    description: "Ensure annotations are up to date"
    command: ["./bin/annotate-check"]
  BundleCheck:
    enabled: true

