require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: never

Style/NegatedIf:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/FilePath:
  Enabled: true
  EnforcedStyle: arguments